export { default as Header } from './Header';
export { default as HeroSection } from './HeroSection';
export { default as IntroSection } from './IntroSection';
export { default as BenefitsSection } from './BenefitsSection';
export { default as JobOffersSection } from './JobOffersSection';
export { default as FAQSection } from './FAQSection';
export { default as TestimonialsSection } from './TestimonialsSection';
export { default as CTASection } from './CTASection';
export { default as Footer } from './Footer'; 